[package]
name = "minimizer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
corpus = { workspace = true }
differential = { workspace = true }
runner = { workspace = true }
target-api = { workspace = true }
model = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
